PAL_NAMES = {
    "SheepBall": "Lamball",
    "Quest_Farmer03_SheepBall": "Lamball",
    "BOSS_SheepBall": "Big Floof Lamball",
    "PinkCat": "Cattiva",
    "Quest_Farmer03_PinkCat": "Cattiva",
    "BOSS_PinkCat": "The Cat's Pajamas Cattiva",
    "ChickenPal": "Chikipi",
    "BOSS_ChickenPal": "Plump & Juicy Chikipi",
    "Carbunclo": "Lifmunk",
    "BOSS_Carbunclo": "Coward of the Steppe Lifmunk",
    "Kitsunebi": "Foxparks",
    "BOSS_Kitsunebi": "Revealer of Paths Foxparks",
    "Kitsunebi_Ice": "Foxparks Cryst",
    "BOSS_Kitsunebi_Ice": "Icy Blossom Voyager Foxparks Cryst",
    "BluePlatypus": "Fuack",
    "BOSS_BluePlatypus": "Rowdy Wave Ripper Fuack",
    "BluePlatypus_Fire": "Fuack Ignis",
    "BOSS_BluePlatypus_Fire": "Runaway Wave Rider Fuack Ignis",
    "ElecCat": "Sparkit",
    "BOSS_ElecCat": "Livewire Tabby Sparkit",
    "Monkey": "Tanzee",
    "BOSS_Monkey": "Dexterous Primate Tanzee",
    "FlameBambi": "Rooby",
    "BOSS_FlameBambi": "Chief of the Herd Rooby",
    "Penguin": "Pengullet",
    "BOSS_Penguin": "Ate Too Much Pengullet",
    "Penguin_Electric": "Pengullet Lux",
    "BOSS_Penguin_Electric": "Had One Too Many Pengullet Lux",
    "CaptainPenguin": "Penking",
    "BOSS_CaptainPenguin": "Pioneer of the Frozen Sea Penking",
    "CaptainPenguin_Black": "Penking Lux",
    "BOSS_CaptainPenguin_Black": "Pioneer of the Black Penking Lux",
    "Hedgehog": "Jolthog",
    "BOSS_Hedgehog": "Don't Touch! Jolthog",
    "Hedgehog_Ice": "Jolthog Cryst",
    "BOSS_Hedgehog_Ice": "Watch Your Feet! Jolthog Cryst",
    "PlantSlime": "Gumoss",
    "PlantSlime_Flower": "Gumoss (Flower)",
    "BOSS_PlantSlime_Flower": "Gumoss (Flower)",
    "BOSS_PlantSlime": "Suddenly Transformed Gumoss",
    "CuteFox": "Vixy",
    "BOSS_CuteFox": "Star of the Steppe Vixy",
    "WizardOwl": "Hoocrates",
    "BOSS_WizardOwl": "Purveyor of Wisdom Hoocrates",
    "Ganesha": "Teafant",
    "BOSS_Ganesha": "Adorable Watering Can Teafant",
    "NegativeKoala": "Depresso",
    "BOSS_NegativeKoala": "Several Sleepless Nights Later Depresso",
    "WoolFox": "Cremis",
    "BOSS_WoolFox": "Darling Furball Cremis",
    "DreamDemon": "Daedream",
    "BOSS_DreamDemon": "Daedream",
    "Boar": "Rushoar",
    "BOSS_Boar": "Woodland Ruffian Rushoar",
    "NightFox": "Nox",
    "BOSS_NightFox": "Dusken Aristocrat Nox",
    "CuteMole": "Fuddler",
    "BOSS_CuteMole": "Underground Explorer Fuddler",
    "NegativeOctopus": "Killamari",
    "BOSS_NegativeOctopus": "Emotionless Killamari",
    "NegativeOctopus_Neutral": "Killamari Primo",
    "BOSS_NegativeOctopus_Neutral": "Devoid of Emotion Killamari Primo",
    "Bastet": "Mau",
    "BOSS_Bastet": "Noble Glimmer Mau",
    "Bastet_Ice": "Mau Cryst",
    "BOSS_Bastet_Ice": "Serene Glimmer Mau Cryst",
    "FlyingManta": "Celaray",
    "BOSS_FlyingManta": "Soaring Skyfish Celaray",
    "FlyingManta_Thunder": "Celaray Lux",
    "BOSS_FlyingManta_Thunder": "Sky-Swimming Fish Celaray Lux",
    "Garm": "Direhowl",
    "PREDATOR_Garm": "Rampaging Direhowl",
    "BOSS_Garm": "Hunter of the Steppe Direhowl",
    "ColorfulBird": "Tocotoco",
    "BOSS_ColorfulBird": "Boom or Bust Tocotoco",
    "FlowerRabbit": "Flopie",
    "BOSS_FlowerRabbit": "Star of the Flower Beds Flopie",
    "CowPal": "Mozzarina",
    "BOSS_CowPal": "Grade A Beef Mozzarina",
    "LittleBriarRose": "Bristla",
    "BOSS_LittleBriarRose": "Thorny Rose Bristla",
    "SharkKid": "Gobfin",
    "BOSS_SharkKid": "Sea Thug Gobfin",
    "SharkKid_Fire": "Gobfin Ignis",
    "BOSS_SharkKid_Fire": "Volcano Thug Gobfin Ignis",
    "WindChimes": "Hangyu",
    "BOSS_WindChimes": "Bringer of Luck Hangyu",
    "WindChimes_Ice": "Hangyu Cryst",
    "BOSS_WindChimes_Ice": "Glacial Harbinger Hangyu Cryst",
    "GrassPanda": "Mossanda",
    "PREDATOR_GrassPanda": "Rampaging Mossanda",
    "BOSS_GrassPanda": "Guardian of the Forest Mossanda",
    "GrassPanda_Electric": "Mossanda Lux",
    "BOSS_GrassPanda_Electric": "Inheritor of the Storm Mossanda Lux",
    "SweetsSheep": "Woolipop",
    "BOSS_SweetsSheep": "Giant Cotton Candy Woolipop",
    "BerryGoat": "Caprity",
    "BOSS_BerryGoat": "Walking Farm Caprity",
    "BerryGoat_Dark": "Caprity Noct",
    "BOSS_BerryGoat_Dark": "Tainted Farm Caprity Noct",
    "Alpaca": "Melpaca",
    "BOSS_Alpaca": "Pompous Shanks Melpaca",
    "Deer": "Eikthyrdeer",
    "BOSS_Deer": "Protector of the Herd Eikthyrdeer",
    "Deer_Ground": "Eikthyrdeer Terra",
    "BOSS_Deer_Ground": "Antler of Gold Eikthyrdeer Terra",
    "HawkBird": "Nitewing",
    "BOSS_HawkBird": "Wings of the Firmament Nitewing",
    "PinkRabbit": "Ribbuny",
    "BOSS_PinkRabbit": "Heart-Melting Smile Ribbuny",
    "PinkRabbit_Grass": "Ribbuny Botan",
    "BOSS_PinkRabbit_Grass": "Sparkling Smile Ribbuny Botan",
    "Baphomet": "Incineram",
    "BOSS_Baphomet": "Hyena of the Wild Incineram",
    "Baphomet_Dark": "Incineram Noct",
    "Baphomet_Dark_Oilrig": "Incineram Noct",
    "PREDATOR_Baphomet_Dark": "Rampaging Incineram Noct",
    "BOSS_Baphomet_Dark": "Hyena of the Darkest Night Incineram Noct",
    "CuteButterfly": "Cinnamoth",
    "BOSS_CuteButterfly": "Butterfly Promenade Cinnamoth",
    "FlameBuffalo": "Arsox",
    "BOSS_FlameBuffalo": "Blazing Brute Arsox",
    "LazyCatfish": "Dumud",
    "BOSS_LazyCatfish": "Perpetual Procrastinator Dumud",
    "LazyCatfish_Gold": "Dumud Gild",
    "BOSS_LazyCatfish_Gold": "Piece of Cake Dumud Gild",
    "DarkCrow": "Cawgnito",
    "BOSS_DarkCrow": "Shadow-Cloaked Schemer Cawgnito",
    "LizardMan": "Leezpunk",
    "LizardMan_Oilrig": "Leezpunk",
    "BOSS_LizardMan": "Self-Proclaimed Genius Leezpunk",
    "LizardMan_Fire": "Leezpunk Ignis",
    "BOSS_LizardMan_Fire": "Self-Proclaimed Fashionista Leezpunk Ignis",
    "Werewolf": "Loupmoon",
    "BOSS_Werewolf": "Enraptured by Moonlight Loupmoon",
    "Werewolf_Ice": "Loupmoon Cryst",
    "PREDATOR_Werewolf_Ice": "Rampaging Loupmoon Cryst",
    "BOSS_Werewolf_Ice": "Enraptured by the Frozen Moonlight Loupmoon Cryst",
    "Eagle": "Galeclaw",
    "BOSS_Eagle": "Proud Courier Galeclaw",
    "RobinHood": "Robinquill",
    "BOSS_RobinHood": "Archer of the Forest Robinquill",
    "RobinHood_Ground": "Robinquill Terra",
    "BOSS_RobinHood_Ground": "Archer of the Sands Robinquill Terra",
    "Gorilla": "Gorirat",
    "PREDATOR_Gorilla": "Rampaging Gorirat",
    "BOSS_Gorilla": "Jungle Punk Gorirat",
    "Gorilla_Ground": "Gorirat Terra",
    "BOSS_Gorilla_Ground": "Up for a Brawl Gorirat Terra",
    "SoldierBee": "Beegarde",
    "BOSS_SoldierBee": "Guardian Commander Beegarde",
    "QueenBee": "Elizabee",
    "BOSS_QueenBee": "Empress of the Hive Elizabee",
    "NaughtyCat": "Grintale",
    "BOSS_NaughtyCat": "Marshmallow Body Grintale",
    "MopBaby": "Swee",
    "BOSS_MopBaby": "Curious Floof Swee",
    "MopKing": "Sweepa",
    "BOSS_MopKing": "King of the Floof Sweepa",
    "WeaselDragon": "Chillet",
    "BOSS_WeaselDragon": "Dancer on the Steppe Chillet",
    "WeaselDragon_Fire": "Chillet Ignis",
    "BOSS_WeaselDragon_Fire": "Cherry Blossom Dancer Chillet Ignis",
    "Kirin": "Univolt",
    "BOSS_Kirin": "Swift Deity Univolt",
    "IceFox": "Foxcicle",
    "BOSS_IceFox": "Claws of Ice Foxcicle",
    "FireKirin": "Pyrin",
    "BOSS_FireKirin": "Steed of Flames Pyrin",
    "FireKirin_Dark": "Pyrin Noct",
    "BOSS_FireKirin_Dark": "Steed of Darkness Pyrin Noct",
    "IceDeer": "Reindrix",
    "BOSS_IceDeer": "Frosthorn Beast Reindrix",
    "ThunderDog": "Rayhound",
    "PREDATOR_ThunderDog": "Rampaging Rayhound",
    "BOSS_ThunderDog": "Electro-Charged Zoomies Rayhound",
    "AmaterasuWolf": "Kitsun",
    "PREDATOR_AmaterasuWolf": "Rampaging Kitsun",
    "BOSS_AmaterasuWolf": "Guardian of the Azure Flame Kitsun",
    "AmaterasuWolf_Dark": "Kitsun Noct",
    "BOSS_AmaterasuWolf_Dark": "Guardian of the Dark Flame Kitsun Noct",
    "RaijinDaughter": "Dazzi",
    "BOSS_RaijinDaughter": "Born of the Storm Dazzi",
    "RaijinDaughter_Water": "Dazzi Noct",
    "BOSS_RaijinDaughter_Water": "Born of the Thunderclouds Dazzi Noct",
    "Mutant": "Lunaris",
    "DarkMutant": "DarkMutant",
    "BOSS_DarkMutant": "BOSS_NAME_DarkMutant DarkMutant",
    "BOSS_Mutant": "Extraterrestrial Lunaris",
    "FlowerDinosaur": "Dinossom",
    "PREDATOR_FlowerDinosaur": "Rampaging Dinossom",
    "BOSS_FlowerDinosaur": "Guardian of Blossoming Gardens Dinossom",
    "FlowerDinosaur_Electric": "Dinossom Lux",
    "BOSS_FlowerDinosaur_Electric": "Guardian of Lightning Dinossom Lux",
    "Serpent": "Surfent",
    "BOSS_Serpent": "The Ocean's Wrath Surfent",
    "Serpent_Ground": "Surfent Terra",
    "BOSS_Serpent_Ground": "The Desert's Wrath Surfent Terra",
    "GhostBeast": "Maraith",
    "PREDATOR_GhostBeast": "Rampaging Maraith",
    "BOSS_GhostBeast": "Messenger of Death Maraith",
    "DrillGame": "Digtoise",
    "PREDATOR_DrillGame": "Rampaging Digtoise",
    "BOSS_DrillGame": "Drilling Machine Digtoise",
    "CatBat": "Tombat",
    "BOSS_CatBat": "Trickster Tombat",
    "PinkLizard": "Lovander",
    "PREDATOR_PinkLizard": "Rampaging Lovander",
    "BOSS_PinkLizard": "Pal on the Prowl Lovander",
    "LavaGirl": "Flambelle",
    "BOSS_LavaGirl": "Molten Daughter Flambelle",
    "BirdDragon": "Vanwyrm",
    "PREDATOR_BirdDragon": "Rampaging Vanwyrm",
    "BOSS_BirdDragon": "Aerial Marauder Vanwyrm",
    "BirdDragon_Ice": "Vanwyrm Cryst",
    "BOSS_BirdDragon_Ice": "Marauder of Frozen Skies Vanwyrm Cryst",
    "Ronin": "Bushi",
    "BOSS_Ronin": "Vagrant Warrior Bushi",
    "Ronin_Dark": "Bushi Noct",
    "PREDATOR_Ronin_Dark": "Rampaging Bushi Noct",
    "BOSS_Ronin_Dark": "Samurai of Darkness Bushi Noct",
    "ThunderBird": "Beakon",
    "BOSS_ThunderBird": "Wings of Thunder Beakon",
    "RedArmorBird": "Ragnahawk",
    "PREDATOR_RedArmorBird": "Rampaging Ragnahawk",
    "BOSS_RedArmorBird": "Wings of Inferno Ragnahawk",
    "CatMage": "Katress",
    "BOSS_CatMage": "Phantasmal Feline Katress",
    "CatMage_Fire": "Katress Ignis",
    "BOSS_CatMage_Fire": "Fire Licked Feline Katress Ignis",
    "FoxMage": "Wixen",
    "BOSS_FoxMage": "Fire Licked Furball Wixen",
    "FoxMage_Dark": "Wixen Noct",
    "BOSS_FoxMage_Dark": "Phantasmal Furball Wixen Noct",
    "GrassRabbitMan": "Verdash",
    "BOSS_GrassRabbitMan": "Gale of the Forest Verdash",
    "VioletFairy": "Vaelet",
    "BOSS_VioletFairy": "Voice of the Violets Vaelet",
    "WhiteMoth": "Sibelyx",
    "BOSS_WhiteMoth": "Pallid Lady Sibelyx",
    "FairyDragon": "Elphidran",
    "PREDATOR_FairyDragon": "Rampaging Elphidran",
    "BOSS_FairyDragon": "Gentle Sky Dragon Elphidran",
    "FairyDragon_Water": "Elphidran Aqua",
    "BOSS_FairyDragon_Water": "Beast of the Tides Elphidran Aqua",
    "Kelpie": "Kelpsea",
    "BOSS_Kelpie": "Child of the Deep Kelpsea",
    "Kelpie_Fire": "Kelpsea Ignis",
    "BOSS_Kelpie_Fire": "Child of Molten Depths Kelpsea Ignis",
    "BlueDragon": "Azurobe",
    "BOSS_BlueDragon": "Lady of the Lake Azurobe",
    "BlueDragon_Ice": "Azurobe Cryst",
    "BOSS_BlueDragon_Ice": "Lady of the Frozen Lake Azurobe Cryst",
    "WhiteTiger": "Cryolinx",
    "BOSS_WhiteTiger": "Predator of Snowy Peaks Cryolinx",
    "WhiteTiger_Ground": "Cryolinx Terra",
    "PREDATOR_WhiteTiger_Ground": "Rampaging Cryolinx Terra",
    "BOSS_WhiteTiger_Ground": "Predator of the Earth Cryolinx Terra",
    "Manticore": "Blazehowl",
    "BOSS_Manticore": "Crimson Goliath Blazehowl",
    "Manticore_Dark": "Blazehowl Noct",
    "PREDATOR_Manticore_Dark": "Rampaging Blazehowl Noct",
    "BOSS_Manticore_Dark": "Inferno Goliath Blazehowl Noct",
    "LazyDragon": "Relaxaurus",
    "PREDATOR_LazyDragon": "Rampaging Relaxaurus",
    "BOSS_LazyDragon": "Gluttonous Dragon Relaxaurus",
    "LazyDragon_Electric": "Relaxaurus Lux",
    "BOSS_LazyDragon_Electric": "Gluttonous Thunder Dragon Relaxaurus Lux",
    "SakuraSaurus": "Broncherry",
    "BOSS_SakuraSaurus": "Winds of Spring Broncherry",
    "SakuraSaurus_Water": "Broncherry Aqua",
    "BOSS_SakuraSaurus_Water": "Waves of Summer Broncherry Aqua",
    "FlowerDoll": "Petallia",
    "BOSS_FlowerDoll": "Lady of the Flower Garden Petallia",
    "VolcanicMonster": "Reptyro",
    "BOSS_VolcanicMonster": "Lava-Devouring Juggernaut Reptyro",
    "VolcanicMonster_Ice": "Reptyro Cryst",
    "PREDATOR_VolcanicMonster_Ice": "Rampaging Reptyro Cryst",
    "BOSS_VolcanicMonster_Ice": "Ice-Breaking Juggernaut Reptyro Cryst",
    "KingAlpaca": "Kingpaca",
    "BOSS_KingAlpaca": "Supreme Fluff Commander Kingpaca",
    "KingAlpaca_Ice": "Kingpaca Cryst",
    "BOSS_KingAlpaca_Ice": "Azure Fluff Commander Kingpaca Cryst",
    "GrassMammoth": "Mammorest",
    "BOSS_GrassMammoth": "King of the Forest Mammorest",
    "GrassMammoth_Ice": "Mammorest Cryst",
    "BOSS_GrassMammoth_Ice": "Frozen King Mammorest Cryst",
    "Yeti": "Wumpo",
    "PREDATOR_Yeti": "Rampaging Wumpo",
    "BOSS_Yeti": "Guardian of the Snowy Mountain Wumpo",
    "Yeti_Grass": "Wumpo Botan",
    "BOSS_Yeti_Grass": "Guardian of the Grassy Fields Wumpo Botan",
    "HerculesBeetle": "Warsect",
    "BOSS_HerculesBeetle": "Unyielding Colossus Warsect",
    "HerculesBeetle_Ground": "Warsect Terra",
    "BOSS_HerculesBeetle_Ground": "Golden Armor Warrior Warsect Terra",
    "FengyunDeeper": "Fenglope",
    "BOSS_FengyunDeeper": "Drifting Cloud Fenglope",
    "FengyunDeeper_Electric": "Fenglope Lux",
    "BOSS_FengyunDeeper_Electric": "Drifting Thundercloud Fenglope Lux",
    "CatVampire": "Felbat",
    "BOSS_CatVampire": "Gloom-Shrouded Bloodsucker Felbat",
    "SkyDragon": "Quivern",
    "BOSS_SkyDragon": "Snow-White Soarer Quivern",
    "SkyDragon_Grass": "Quivern Botan",
    "BOSS_SkyDragon_Grass": "Evergreen Flyer Quivern Botan",
    "KingBahamut": "Blazamut",
    "BOSS_KingBahamut": "Cursed Tyrant Blazamut",
    "KingBahamut_Dragon": "Blazamut Ryu",
    "BOSS_KingBahamut_Dragon": "Incarnation of the Eternal Flame Blazamut Ryu",
    "RAID_KingBahamut_Dragon_2": "Incarnation of the Eternal Flame (Ultra) Blazamut Ryu",
    "RAID_KingBahamut_Dragon": "Incarnation of the Eternal Flame Blazamut Ryu",
    "HadesBird": "Helzephyr",
    "HadesBird_Oilrig": "Helzephyr",
    "BOSS_HadesBird": "Wings of The Underworld Helzephyr",
    "HadesBird_Electric": "Helzephyr Lux",
    "PREDATOR_HadesBird_Electric": "Rampaging Helzephyr Lux",
    "BOSS_HadesBird_Electric": "Wings of Thunder Helzephyr Lux",
    "BlackMetalDragon": "Astegon",
    "BOSS_BlackMetalDragon": "Monarch of the Steel Dragon Astegon",
    "DarkScorpion": "Menasting",
    "BOSS_DarkScorpion": "Unstoppable Stinger Menasting",
    "DarkScorpion_Ground": "Menasting Terra",
    "BOSS_DarkScorpion_Ground": "Gold-Piercing Spear Menasting Terra",
    "Anubis": "Anubis",
    "Boss_Anubis": "Guardian of the Dark Sun Anubis",
    "Umihebi": "Jormuntide",
    "BOSS_Umihebi": "Emperor of the Sea Jormuntide",
    "Umihebi_Fire": "Jormuntide Ignis",
    "PREDATOR_Umihebi_Fire": "Rampaging Jormuntide Ignis",
    "BOSS_Umihebi_Fire": "Volcanic Emperor Jormuntide Ignis",
    "Suzaku": "Suzaku",
    "BOSS_Suzaku": "Ruler of the Crimson Dawn Suzaku",
    "Suzaku_Water": "Suzaku Aqua",
    "BOSS_Suzaku_Water": "Ruler of the Cobalt Dusk Suzaku Aqua",
    "ElecPanda": "Grizzbolt",
    "GYM_ElecPanda_Otomo": "Zoe & Grizzbolt",
    "BOSS_ElecPanda": "Claws of Lightning Grizzbolt",
    "GYM_ElecPanda_2": "Zoe & Grizzbolt II",
    "GYM_ElecPanda": "Zoe & Grizzbolt",
    "LilyQueen": "Lyleen",
    "BOSS_LilyQueen": "Lily Empress Lyleen",
    "GYM_LilyQueen_2": "Lily & Lyleen II",
    "GYM_LilyQueen": "Lily & Lyleen",
    "LilyQueen_Dark": "Lyleen Noct",
    "BOSS_LilyQueen_Dark": "Empress of the Abyss Lyleen Noct",
    "Horus": "Faleris",
    "Horus_Oilrig": "Faleris",
    "BOSS_Horus": "Sentinel of Dawn Faleris",
    "GYM_Horus_2": "Marcus & Faleris II",
    "GYM_Horus": "Marcus & Faleris",
    "Horus_Water": "Faleris Aqua",
    "PREDATOR_Horus_Water": "Rampaging Faleris Aqua",
    "BOSS_Horus_Water": "Sentinel of the Tides Faleris Aqua",
    "ThunderDragonMan": "Orserk",
    "BOSS_ThunderDragonMan": "Roaring Thunder Orserk",
    "GYM_ThunderDragonMan_2": "Axel & Orserk II",
    "GYM_ThunderDragonMan": "Axel & Orserk",
    "BlackGriffon": "Shadowbeak",
    "BOSS_BlackGriffon": "Unknown Life Form Shadowbeak",
    "GYM_BlackGriffon_2_Avatar": "Victor & Shadowbeak",
    "GYM_BlackGriffon_2": "Victor & Shadowbeak II",
    "GYM_BlackGriffon": "Victor & Shadowbeak",
    "SaintCentaur": "Paladius",
    "BOSS_SaintCentaur": "Holy Knight of Legend Paladius",
    "BlackCentaur": "Necromus",
    "BOSS_BlackCentaur": "Dark Knight of Legend Necromus",
    "IceHorse": "Frostallion",
    "BOSS_IceHorse": "Legendary Steed of Ice Frostallion",
    "IceHorse_Dark": "Frostallion Noct",
    "BOSS_IceHorse_Dark": "Legendary Steed of Darkness Frostallion Noct",
    "JetDragon": "Jetragon",
    "BOSS_JetDragon": "Legendary Celestial Dragon Jetragon",
    "NightLady": "Bellanoir",
    "BOSS_NightLady": "Eclipsed Siren Bellanoir",
    "RAID_NightLady": "Eclipsed Siren Bellanoir",
    "NightLady_Dark": "Bellanoir Libero",
    "BOSS_NightLady_Dark": "Twilight Siren Bellanoir Libero",
    "RAID_NightLady_Dark_2": "Twilight Siren (Ultra) Bellanoir Libero",
    "RAID_NightLady_Dark": "Twilight Siren Bellanoir Libero",
    "MoonQueen": "Selyne",
    "BOSS_MoonQueen": "Crescent of the Darkest Night Selyne",
    "GYM_MoonQueen_2_Servant": "Selyne",
    "GYM_MoonQueen_2": "Saya & Selyne II",
    "GYM_MoonQueen": "Saya & Selyne",
    "KendoFrog": "Croajiro",
    "BOSS_KendoFrog": "Harakiri Master Croajiro",
    "KendoFrog_Dark": "Croajiro Noct",
    "BOSS_KendoFrog_Dark": "Natural Born Killer Croajiro Noct",
    "LeafPrincess": "Lullu",
    "BOSS_LeafPrincess": "Primal Source of Hay Fever Lullu",
    "MushroomDragon": "Shroomer",
    "PREDATOR_MushroomDragon": "Rampaging Shroomer",
    "BOSS_MushroomDragon": "Creeping Mushroom Shroomer",
    "MushroomDragon_Dark": "Shroomer Noct",
    "BOSS_MushroomDragon_Dark": "Dangerous Mushroom Shroomer Noct",
    "SmallArmadillo": "Kikit",
    "BOSS_SmallArmadillo": "Armored to the Teeth Kikit",
    "CandleGhost": "Sootseer",
    "PREDATOR_CandleGhost": "Rampaging Sootseer",
    "BOSS_CandleGhost": "Flickering Flame Sootseer",
    "ScorpionMan": "Prixter",
    "PREDATOR_ScorpionMan": "Rampaging Prixter",
    "BOSS_ScorpionMan": "Bad Boy Prixter",
    "WingGolem": "Knocklem",
    "WingGolem_Oilrig": "Knocklem",
    "BOSS_WingGolem": "Suit of Armor Knocklem",
    "GuardianDog": "Yakumo",
    "BOSS_GuardianDog": "Unwavering Loyalty Yakumo",
    "SifuDog": "Dogen",
    "PREDATOR_SifuDog": "Rampaging Dogen",
    "BOSS_SifuDog": "State of Enlightenment Dogen",
    "FeatherOstrich": "Dazemu",
    "PREDATOR_FeatherOstrich": "Rampaging Dazemu",
    "BOSS_FeatherOstrich": "Brilliant Steps Dazemu",
    "MimicDog": "Mimog",
    "BOSS_MimicDog": "Treasure Trove Mimog",
    "DarkAlien": "Xenovader",
    "DarkAlien_Oilrig": "Xenovader",
    "SUMMON_DarkAlien_MAX": "Xenovader",
    "SUMMON_DarkAlien": "Xenovader",
    "BOSS_DarkAlien": "Interloper from Outer Space Xenovader",
    "WhiteAlienDragon": "Xenogard",
    "SUMMON_WhiteAlienDragon_MAX": "Xenogard",
    "SUMMON_WhiteAlienDragon": "Xenogard",
    "BOSS_WhiteAlienDragon": "Planet-Devouring Dragon Xenogard",
    "DarkMechaDragon": "Xenolord",
    "RAID_DarkMechaDragon_2": "Invader from Space (Ultra) Xenolord",
    "RAID_DarkMechaDragon": "Invader from Space Xenolord",
    "BOSS_DarkMechaDragon": "Invader from Space Xenolord",
    "GhostRabbit": "Nitemary",
    "BOSS_GhostRabbit": "Soul of the Dark Rabbit Nitemary",
    "NightBlueHorse": "Starryon",
    "PREDATOR_NightBlueHorse": "Rampaging Starryon",
    "BOSS_NightBlueHorse": "Midnight Blue Mane Starryon",
    "WhiteShieldDragon": "Silvegis",
    "BOSS_WhiteShieldDragon": "Guardian Dragon of Ironclad Silvegis",
    "BlackPuppy": "Smokie",
    "BOSS_BlackPuppy": "Jet-Black Little Hero Smokie",
    "WhiteDeer": "Celesdir",
    "BOSS_WhiteDeer": "Beast of Salvation Celesdir",
    "MysteryMask": "Omascul",
    "PREDATOR_MysteryMask": "Rampaging Omascul",
    "BOSS_MysteryMask": "Hundred-Faced Apostle Omascul",
    "GrimGirl": "Splatterina",
    "PREDATOR_GrimGirl": "Rampaging Splatterina",
    "BOSS_GrimGirl": "Crimson Butcher Splatterina",
    "PurpleSpider": "Tarantriss",
    "PREDATOR_PurpleSpider": "Rampaging Tarantriss",
    "BOSS_PurpleSpider": "Tactician of the Thread Realm Tarantriss",
    "BlueThunderHorse": "Azurmane",
    "BOSS_BlueThunderHorse": "Blue Lightning Steed Azurmane",
    "SnowTigerBeastman": "Bastigor",
    "GYM_SnowTigerBeastman_2": "Bjorn & Bastigor II",
    "GYM_SnowTigerBeastman": "Bjorn & Bastigor",
    "BOSS_SnowTigerBeastman": "King of Frostfang Bastigor",
    "BlueberryFairy": "Prunelia",
    "BOSS_BlueberryFairy": "Indigo Handmaiden Prunelia",
    "BadCatgirl": "Nyafia",
    "BOSS_BadCatgirl": "Night Shade Hunter Nyafia",
    "GoldenHorse": "Gildane",
    "PREDATOR_GoldenHorse": "Rampaging Gildane",
    "BOSS_GoldenHorse": "Guardian Beast of Twilight Gildane",
    "LeafMomonga": "Herbil",
    "BOSS_LeafMomonga": "Percussive Maintenance Herbil",
    "IceWitch": "Icelyn",
    "BOSS_IceWitch": "Icy Smile Icelyn",
    "SnowPeafowl": "Frostplume",
    "BOSS_SnowPeafowl": "Snowlaced Feather Mantle Frostplume",
    "TropicalOstrich": "Palumba",
    "BOSS_TropicalOstrich": "No Dance, No Life Palumba",
    "Plesiosaur": "Braloha",
    "BOSS_Plesiosaur": "Ancient Bloombringer Braloha",
    "IceCrocodile": "Munchill",
    "BOSS_IceCrocodile": "Walking Refrigerator Munchill",
    "IceSeal": "Polapup",
    "BOSS_IceSeal": "Idol on Ice Polapup",
    "TentacleTurtle": "Turtacle",
    "BOSS_TentacleTurtle": "Mini Fortress Turtacle",
    "TentacleTurtle_Ground": "Turtacle Terra",
    "BOSS_TentacleTurtle_Ground": "Golden Fortress Turtacle Terra",
    "JellyfishGhost": "Jellroy",
    "BOSS_JellyfishGhost": "Shade Drifter Jellroy",
    "JellyfishFairy": "Jelliette",
    "BOSS_JellyfishFairy": "Sunlight Drifter Jelliette",
    "OctopusGirl": "Gloopie",
    "BOSS_OctopusGirl": "Trickster of the Sea Gloopie",
    "StuffedShark": "Finsider",
    "BOSS_StuffedShark": "Eyes from the Abyss Finsider",
    "StuffedShark_Fire": "Finsider Ignis",
    "BOSS_StuffedShark_Fire": "Eyes from the Flames Finsider Ignis",
    "GhostAnglerfish": "Ghangler",
    "BOSS_GhostAnglerfish": "Temptation in the Deep Ghangler",
    "GhostAnglerfish_Fire": "Ghangler Ignis",
    "BOSS_GhostAnglerfish_Fire": "Longing in the Deep Ghangler Ignis",
    "IceNarwhal": "Whalaska",
    "BOSS_IceNarwhal": "Nice Ice Lance Whalaska",
    "IceNarwhal_Fire": "Whalaska Ignis",
    "BOSS_IceNarwhal_Fire": "Nice Crimson Lance Whalaska Ignis",
    "PoseidonOrca": "Neptilius",
    "BOSS_PoseidonOrca": "Legend of the Seas Neptilius",
    "YakushimaMonster001": "Green Slime",
    "YakushimaMonster001_Blue": "Blue Slime",
    "YakushimaMonster001_Red": "Red Slime",
    "YakushimaMonster001_Purple": "Purple Slime",
    "YakushimaMonster001_Pink": "Illuminant Slime",
    "YakushimaMonster001_Rainbow": "Rainbow Slime",
    "YakushimaMonster002": "Enchanted Sword",
    "YakushimaMonster003": "Cave Bat",
    "YakushimaMonster003_Purple": "Illuminant Bat",
    "YakushimaBoss001": "Eye of Cthulhu",
    "BOSS_YakushimaBoss001": "Eye of Cthulhu",
    "YakushimaBoss001_Small": "Demon Eye",
    "RAID_YakushimaBoss001_Green": "True Eye of Cthulhu",
    "RAID_YakushimaBoss002": "Moon Lord"
}